workflows:
  ios-build:
    name: Build iOS App
    environment:
      node: 18.16.0
    scripts:
      - npm install
      - npm install -g @capacitor/cli
      - echo "No build step needed"
      - npx cap sync ios
    artifacts:
      - ios/App/build/*.ipa
