workflows:
  ios-build:
    name: Build iOS App
    environment:
      node: 18.16.0
    scripts:
      - npm install
      - echo "No build step needed"
      - node_modules/.bin/cap sync ios
    artifacts:
      - ios/App/build/*.ipa
